
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftPLUSMINUSleftMULTMINUS MULT NUMBER PLUSexpression : expression PLUS termexpression : expression MINUS termexpression : termterm : term MULT factorterm : factorfactor : NUMBER'
    
_lr_action_items = {'NUMBER':([0,5,6,7,],[4,4,4,4,]),'$end':([1,2,3,4,8,9,10,],[0,-3,-5,-6,-1,-2,-4,]),'PLUS':([1,2,3,4,8,9,10,],[5,-3,-5,-6,-1,-2,-4,]),'MINUS':([1,2,3,4,8,9,10,],[6,-3,-5,-6,-1,-2,-4,]),'MULT':([2,3,4,8,9,10,],[7,-5,-6,7,7,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),'term':([0,5,6,],[2,8,9,]),'factor':([0,5,6,7,],[3,3,3,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression PLUS term','expression',3,'p_expression_plus','parser.py',45),
  ('expression -> expression MINUS term','expression',3,'p_expression_minus','parser.py',49),
  ('expression -> term','expression',1,'p_expression_term','parser.py',54),
  ('term -> term MULT factor','term',3,'p_term_mult','parser.py',59),
  ('term -> factor','term',1,'p_term_factor','parser.py',64),
  ('factor -> NUMBER','factor',1,'p_factor_number','parser.py',69),
]
